### PR TITLE
Make compatible with Sprockets 3.0.0.beta.8.

### PR DESCRIPTION
**Pull request by tatey**
Firstly, thanks for putting together this library.

I'm setting up a new nanoc project and noticed it's not working with the latest beta of Sprockets. If I understand the dependency tracking correctly, this patch should do the trick.

### CODE REVIEW

**Comment by tatey** [comment]
Forgot to mention, this probably isn't backwards compatible with earlier versions.

**Comment by barraq** [comment]
Hi @tatey, indeed I am currently discussing with @josh (author of Sprockets) about this issue (see the end of discussion here https://github.com/sstephenson/sprockets/issues/673). In fact what I was using to access dependency paths in Sprockets 3.0.0.beta.6 was removed/changed in new beta version.
As soon as I find a way to fix this I will update nanoc-sprockets :p until then you will have to force the use of Sprockets 3.0.0.beta.6 :/

**Comment by tatey** [comment]
Okay, thanks.

**Comment by barraq** [comment]
@tatey version 1.0.3 is now compatible with Sprockets 3.0.0.beta.8 ;)
\cc @josh

**Comment by tatey** [comment]
Cheers :tada:

**Pull request closed without merging**
